db: fix building with gcc 15
gcc 15 enfaces compatible pointers. This causes building db to fail
with:

../src/env/env_config.c:75:36: error: initialization of 'int (*)(void)' from incompatible pointer type 'int (*)(DB_ENV *, const char *)' {aka 'int (*)(struct __db_env *, const char *)'} [-Wincompatible-pointer-types]

The pointers are used correctly just not cast as needed. So explicitly
disable the warning for now.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>